spring:
  datasource:
    username: loanDB
    password: 123456
    url: jdbc:mysql://106.15.203.32:3306/loanDB?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.stu.mapper/*Mapper.xml
  type-aliases-package: com.stu.entity

#showSql
logging:
  level:
    com:
      stu:
        mapper: debug


#redis的配置
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1




##配置分页插件pagehelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


#  #服务器文件存放路径
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/itstyle/, file:/
#  servlet:
#    #上传文件大小限制
#   multipart:
#     max-request-size: 10MB
#     max-file-size: 10MB

